# Generated by Django 5.0.4 on 2024-04-16 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_author_category_remove_book_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Enter the name of the author', null=True, on_delete=django.db.models.deletion.CASCADE, to='market.author', verbose_name='Author Name'),
        ),
    ]
